### ISSUE TITLE
Installation on extensions.gnome.org not working

### ISSUE THREAD

**Issue by varakh** [ChWick/gnomesome#1]
Hi,

I've tried to install your extension by pressing the button on [GNOME Extensions Website](https://extensions.gnome.org/extension/1268/gnomesome/) and it immediately jumps back to "OFF". Any idea?

Regards,
Varakh

**Comment by ChWick** [comment]
On what platform/gnome version are you attempting to install the extension?
1. Can you test if the manual installation (from source of gitlab) works?
2. Can you provide the log output (e. g. journalctl) when you try to enable the extension?

**Comment by varakh** [comment]
Hi,

I'm on ArchLinux, latest GNOME stable release with chromium enabled gnome shell extension to install extensions by visiting the website.

I made a small screencast, so you can see the behaviour yourself: [https://paste.hoth.one/vCa6q/](https://paste.hoth.one/vCa6q/)

I don't see an error in the log, but here it is:

`Aug 11 15:11:25 ziost org.gnome.Shell.desktop[564]: Archive:  /tmp/575M4Y.shell-extension.zip
Aug 11 15:11:25 ziost org.gnome.Shell.desktop[564]:   inflating: /home/alexander/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/extension.js
Aug 11 15:11:25 ziost org.gnome.Shell.desktop[564]:   inflating: /home/alexander/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/convenience.js
Aug 11 15:11:25 ziost org.gnome.Shell.desktop[564]:   inflating: /home/alexander/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/menubutton.js
Aug 11 15:11:25 ziost org.gnome.Shell.desktop[564]:   inflating: /home/alexander/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/schemas/gschemas.compiled
Aug 11 15:11:25 ziost org.gnome.Shell.desktop[564]:   inflating: /home/alexander/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/manager.js
Aug 11 15:11:25 ziost org.gnome.Shell.desktop[564]:   inflating: /home/alexander/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/schemas/org.gnome.shell.extensions.gnomesome.keybindings.gschema.xml
Aug 11 15:11:25 ziost org.gnome.Shell.desktop[564]:   inflating: /home/alexander/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/schemas/org.gnome.shell.extensions.gnomesome.gschema.xml
Aug 11 15:11:25 ziost org.gnome.Shell.desktop[564]:  extracting: /home/alexander/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/metadata.json`

I will later try to install it manually.

**Comment by ChWick** [comment]
I can confirm this on a Fedora 26 Virtual Machine. I will fix this asap!

**Comment by ChWick** [comment]
Fixed with the current version of the extension on the gnome extensions page.
