### ISSUE TITLE
Desktop being treated as a window

### ISSUE THREAD

**Issue by simontong** [ChWick/gnomesome#11]
I have nemo-desktop running to get desktop icons appearing and gnomesome looks like its treating this as another window and tiling a blank gap.

Would it make sense to have an option to list specific programs from being tiled?

**Comment by ghuls** [comment]
@ChWick Not sure if it is intentional or not: `Mod4+j` and `Mod4+k` also cycles trough the desktop window. It was not what I expected. When the desktop window is selected `Mod4+Shift+f` would make the desktop full screen and hide the dock.
