### ISSUE TITLE
Shortcuts for specific layouts

### ISSUE THREAD

**Issue by simontong** [ChWick/gnomesome#12]
Currently we have shortcuts to cycle layouts, would it be possible to specify shortcuts for floating layout / horizontal layout / vertical layout so you can easily toggle between them?

**Comment by ChWick** [comment]
Do you have suggestions for the default keybindings? I propose:
* `Meta + Strg + H`: Horizontal
* `Meta + Strg + V`: Vertical
* `Meta + Strg + F`: Floating
* `Meta + Strg + M`: Maximized
