### ISSUE TITLE
Error loading extension after update

### ISSUE THREAD

**Issue by rehaby** [ChWick/gnomesome#14]
gnome-tweak and gnome extensions are reporting an errors to load the extension. With this error the plugin is not working

**Comment by ChWick** [comment]
Could you please post the error message, you operating system and the gnome-version you are using? Thanks!

**Comment by rehaby** [comment]
Sorry, The error I was getting was a little yellow triangle next to the on/off toggle that said the extension failed to load. I'm using Ubuntu 18.04 with gnome version 3.28.2. I reverted to the previous version. If you can tell me how to get a better error log I can update my extension version and get a log for you

**Comment by ChWick** [comment]
Can you check if clutter is installed:
`sudo apt install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0`

**Comment by rehaby** [comment]
I installed the above packages, checked out master and installed it. I get the same issue before with the 'error loading extension' message in gnome tweak

**Comment by ChWick** [comment]
I experienced the same error on a clean 18.04 machine, and fixed the bug. Thanks!

**Comment by rehaby** [comment]
Can also confirm that it's fixed. Thanks
