### ISSUE TITLE
Extension won't load after update

### ISSUE THREAD

**Issue by daveriedstra** [ChWick/gnomesome#29]
After updating via extensions.gnome.org and restarting my wayland session (via logout/login), the extension no longer loads. `journalctl` shows these errors:

```
gnome-shell[5730]: Some code accessed the property 'SHOW_INPUT_SLIDER' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously sup
gnome-shell[5730]: Extension "gnomesome@chwick.github.com" had error: ImportError: No JS module 'thirdparty' found in search path
```

I'm on Ubuntu 18.04 with Gnome 3.28.2. #14 possibly related.

Thanks for an otherwise _awesome_ extension!

**Comment by coredump** [comment]
Can confirm also not working on Manjaro with latest gnome. Same error, can't import `thirdparty` module.

**Comment by spq** [comment]
can confirm, downgrading helped...

**Comment by ChWick** [comment]
Thanks for the report! I forgot to add the new thirdparty directory to the deployment Makefile... However, you may need to wait for the Gnome team to approve the new upgrade, this may take some days.
