### ISSUE TITLE
Error on opening settings

### ISSUE THREAD

**Issue by Industrial** [ChWick/gnomesome#33]
Hi!

I'd love to try this but when I open the settings I'm getting this error now:

```
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  @/home/tom/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/convenience.js:8:7
  @/home/tom/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/gnomesome_settings.js:6:7
  @/home/tom/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/prefs.js:7:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:67:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
  
```

**Comment by ChWick** [comment]
Did you install
```
sudo apt install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0
```

**Comment by Industrial** [comment]
No, I did not. Sorry, I didn't read the docs fully / properly.

**Comment by Industrial** [comment]
I just installed it, tried it and I'm amazed at the simplicity and speed!

Moved from Xmonad to this and now I don't have to worry about "How do I configure my Wifi", Sound, Bluetooth, etc. Sanity, finally! Best of both worlds combined :-)

Kudos for this application. :+1: 

p.s. open a donation page or something :D

**Comment by ChWick** [comment]
> Moved from Xmonad to this and now I don't have to worry about "How do I configure my Wifi", Sound, Bluetooth, etc. Sanity, finally! Best of both worlds combined :-)

This was exactly the reason why I started this project. :-)
