### ISSUE TITLE
Gnomesome crashes

### ISSUE THREAD

**Issue by mutlusun** [ChWick/gnomesome#35]
Hello,

with the latest release gnomesome crashes with following line in log:
```
gnomesome_chwick.github.com has error: TypeError: this.gslayout is null
```

I tried to fix this error message inserting an if [here](https://github.com/ChWick/gnomesome/blob/e0cb5bf9ac04b7ebc41572b625ffee22e752deb9/gswindow.js#L57-L60):

```{js}
    destroy: function() {
        if (this.gslayout) {
            this.gslayout.removeGSWindow(this);
        }
        this.window.gswindow = undefined;
    },
```

I'm not sure whether there are any unintended consequences ...

Best

**Comment by ChWick** [comment]
Thanks!

**Comment by daveriedstra** [comment]
just encountered this. restarting X fixed it. :man_shrugging:
