### ISSUE TITLE
Loosing keybindings sometimes

### ISSUE THREAD

**Issue by soebbing** [ChWick/gnomesome#47]
Unfortunatly, this isn't reproducible easily, but Gnomesome looses it's keybindings multiple times over the course of a day for me.

E.g. I switch to another workspace with Super+3 just fine, but when I press Super+1 afterwards, Geary is being opend. At that point I just open Gnome Tweaks and reload Gnomesome once to get the bindings back.

If there is any information that might be helpful, I'll happily try to provide it.
GNOME Shell 3.34.5 on NixOS 20.03

**Comment by ChWick** [comment]
Did you disable the dash-to-dock keybindings? See https://github.com/ChWick/gnomesome#disable-dash-to-dock-mod4digit-keybindings

**Comment by soebbing** [comment]
Thanks for the feedback! I didn't, since I thought that wouldn't apply to me due to running NixOS instead of Ubuntu.

I checked in the dconf editor, and there are no dash-to-dock entries there.

**Comment by ChWick** [comment]
However, I expect a similar problem: The shortcuts are used twice (since super+1 launches a program). Could you check if there are entries in the Keyboard Shortcut settings of gnome or any extension that might override the behavior of gnomesome?

**Comment by soebbing** [comment]
I had a look through the extensions and nothing there has any shortcuts overlapping with Gnomesome (if any).

The same is true for the Keyboard Shortcut settings, though I there have settings like these configured:
![image](https://user-images.githubusercontent.com/174161/95972294-906a0700-0e12-11eb-9fd8-973cc2a20735.png)

I actually wasn't aware that the shortcuts I am using to move windows between workspaces (Mod4-Shift-[1-5]) aren't the Gnomesome defaults :smile: 

But still: Where I often happen to stumble across this issue is when I move a window to another workspace with e.g. `Mod4-Shift-3` and want to go back to e.g. to workspace 1 with `Mod4-1`  - `Mod4-1` then opens Geary, I think. `Mod-3` then opens Spotify, though I couldn't find any setting for that.

Again, thank you for helping out!

**Comment by soebbing** [comment]
Just had the case again - it seems it isn't that Gnomesome is loosing the keybindings (`Mod4-3` still moves me to Workspace 3), but it opens Spotify as well. And it does so consistently in that state: If I close Spotify, go to another Workspace and hit `Mod4-3` again, I switch to Workspace 3 and Spotify opens.

After disabling/enabling Gnomesome, Spotify isn't opened anymore

**Comment by ChWick** [comment]
Super+Shift+DIGIT is also the gnomesome default for moving windows.

The error description you are providing is revealing a very, very, very strange behavior. Gnomesome can be part of this problem but gnomesome itself cannot be the reason for it because gnomesome does not launch any program except for the terminal (Mod Enter). In the whole code, there is no such line. Therefore, the question is, who else captures the shortkey (or does somehow interact with gnomesome). And, to be honest, I have absolutely no idea what can cause this strange behavior.

Maybe a related question: Did you pin spotify to the dock/taskbar? And if yes, is it the third program?

Unfortunately, I can not help you out. Sorry for that! But please let me know if you found a solution or - even better - the reason to explain this!

**Comment by soebbing** [comment]
You are right! Spotify is on the third position, Geary on the first in the dock/taskbar!

At least this gives me a pointer, thank you very much! If you have an idea where this is configured, I am happy for any further help - but this definitively is an awesome start - thanks!

**Comment by ChWick** [comment]
Good! This might explain the complete behavior: Hitting Mod+DIGIT launches a program or switches to the running window, but Mod+DIGIT also switches the Workspace.

This is the exact reason why I had to disable all keybindings with:
```
gsettings set org.gnome.shell.keybindings switch-to-application-1 []
gsettings set org.gnome.shell.keybindings switch-to-application-2 []
gsettings set org.gnome.shell.keybindings switch-to-application-3 []
gsettings set org.gnome.shell.keybindings switch-to-application-4 []
gsettings set org.gnome.shell.keybindings switch-to-application-5 []
gsettings set org.gnome.shell.keybindings switch-to-application-6 []
gsettings set org.gnome.shell.keybindings switch-to-application-7 []
gsettings set org.gnome.shell.keybindings switch-to-application-8 []
gsettings set org.gnome.shell.keybindings switch-to-application-9 []
```
Can you check if these entries exist in the dconf editor:
![image](https://user-images.githubusercontent.com/6162410/96152537-f0dd6f00-0f0c-11eb-95d2-e8cb73fbecfe.png)

**Comment by soebbing** [comment]
Found it, my issue is related to this ticket https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1250

Running these commands seem to fix it
```
gsettings set org.gnome.shell.keybindings switch-to-application-1 []
gsettings set org.gnome.shell.keybindings switch-to-application-2 []
gsettings set org.gnome.shell.keybindings switch-to-application-3 []
gsettings set org.gnome.shell.keybindings switch-to-application-4 []
```

**Comment by ChWick** [comment]
perfect!
I will make it clear, that these commands (unset switch-to-application) must be run for all current versions of gnome/ubuntu

**Comment by soebbing** [comment]
Once more: Thank you for your help, even if it didn't have to do anything with your tool!

**Comment by ChWick** [comment]
You are most welcome!
