### ISSUE TITLE
Error on 3.38 again, settings can't be displayed

### ISSUE THREAD

**Issue by maymage** [ChWick/gnomesome#48]
Hi, 

I justed installed the extension again from the gitlab page, as soon as [#46](https://github.com/ChWick/gnomesome/issues/46) was closed. The extension now works, however I cannot access the settings

![Error_Messsage](https://user-images.githubusercontent.com/36572014/97086908-7e644180-1626-11eb-9993-80ef0820ede9.png)

The technical details are 

`Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  @/home/may/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/convenience.js:8:17
  @/home/may/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/gnomesome_settings.js:6:38
  @/home/may/.local/share/gnome-shell/extensions/gnomesome@chwick.github.com/prefs.js:7:27
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Comment by ChWick** [comment]
@maymage Did you install clutter?
`sudo apt install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0`

**Comment by maymage** [comment]
@ChWick 

Okay, stupid me.. I could have sworn to have installed these :(
