### ISSUE TITLE
Take mouse pointer to next screen when selecting next monitor

### ISSUE THREAD

**Issue by mutlusun** [ChWick/gnomesome#7]
Hello,

is it possible with this gnome extension to take the mouse pointer along focus to next screen when pressing `Mod4+Ctrl+[jk]`? Would it be possible to add this as a feature?

Thanks a lot for your work!

**Comment by Industrial** [comment]
This is a must feature IMHO. Right now I can't create new windows on the other monitor after moving a window to the other monitor. I have to grab the mouse and place it there and then create a terminal/window.

**Comment by ChWick** [comment]
I added an option to enable that the pointer follows the focused window. Can you check if this is what you need? Maybe I can set this as default behavior.

**Comment by mutlusun** [comment]
Hello @ChWick ,

thank you for your work! This works as intended ;)

Best

**Comment by Industrial** [comment]
Is this already released? I can't find the option?

![Screenshot](https://i.imgur.com/w3U1tud.png)

**Comment by ChWick** [comment]
@Industrial The code is in the master branch, however not yet available on the gnome extensions page. You need to install gnomesome manually for this feature atm.

**Comment by mutlusun** [comment]
I have tested this feature now for some days and it works quite good for me! Thanks for providing this option.

However, I noticed one drawback: If I have enabled the ["multi-monitors extension"](https://github.com/spin83/multi-monitors-add-on.git), the mouse pointer jumps around when switching to another window on the same monitor (using the keyboard shortcuts provided by gnomesome). I solved this by disabling the multi monitor extension (it is not that necessary for me and can live without it).

Unfortunately, I am out of office for the next two weeks and unable to test any modifications ...

Best

**Comment by ChWick** [comment]
@mutlusun I also use the multi-monitors extension.
What do you mean with 'jumps around'? The current implementation moves the mouse point to the center of a new window if you select another window by Mod+J/K on the same screen. If this is not intended, I can disable that, or add a field to disable this behavior.

**Comment by mutlusun** [comment]
Hello,
sorry for my late reply. Thanks for your clarification! I missed that the mouse pointer move with the focus and not only by switching screens. This works as intended ;)

I ask myself whether some users may be irritated of this behaviour and maybe providing an option for it would be nice. However, I'm fine with changes so far!

Thank you!
